<?php
    include("./registraEmpleado.php");
    if(isset($_POST["nombre"])&&isset($_POST["correo"])&&isset($_POST["especialidad"])&&isset($_POST["contrasena"])){
        $nombre=$_POST["nombre"];
        $correo=$_POST["correo"];
        $especialidad=$_POST["especialidad"];
        $contraseña=$_POST["contrasena"];
        echo(registraEmpleado($nombre,$correo,$especialidad,$contraseña));
    }
?>